Repository vegeten/vegeten-shop, pull requests merged in 2022-06, with the labels that each got.

#18 refactor: 장바구니 상품 수량 증감 리팩토링
  src/views/cart/cart.css
  src/views/cart/cart.html
  src/views/cart/cart.js
  src/views/detail/detail.js
Labels: 프론트엔드, refactor

#31 Feature f order detail
  src/views/detail/detail.css
  src/views/detail/detail.html
  src/views/detail/detail.js
  src/views/mypage/mypage.css
  src/views/mypage/mypage.html
  src/views/mypage/mypage.js
Labels: 프론트엔드, refactor, feature

#35 Feature f detail
  src/views/admin/admin.css
  src/views/admin/admin.html
  src/views/admin/admin.js
  src/views/detail/detail.js
Labels: bug, 프론트엔드

#40 Feature/product refactoring
  src/controllers/category-controller.js
  src/controllers/product-controller.js
  src/routers/category-router.js
  src/routers/product-router.js
  src/routers/search-router.js
Labels: 백엔드, refactor

#53 style: mypage 반응형 디자인
  src/views/mypage/mypage.css
  src/views/mypage/mypage.html
  src/views/mypage/mypage.js
Labels: 프론트엔드

#54 style: home 페이지 반응형 디자인
  src/views/home/home.css
  src/views/home/home.html
Labels: 프론트엔드

#55 Feature f about responsive
  src/views/about/about.css
  src/views/about/about.html
  src/views/home/home.css
  src/views/login/login.css
  src/views/login/login.html
  src/views/login/login.js
  src/views/register/register.css
  src/views/register/register.html
Labels: 프론트엔드

#56 fix: 모바일 뷰 네비게이션에 Log out 버튼 추가 & 로그인 모달 간격 조정
  src/views/components/navigation.js
  src/views/login/login.css
Labels: bug, 프론트엔드
